name: CL

on: [push]

jobs:
  job_3:
    name: CheckHttp
    runs-on: ubuntu-latest
    steps:
      - name: Check
        shell: bash
        run: |
          ver=465
          url=http://120.25.164.233:8080/appstore/app/checkversion?id=21
          newver=$(curl -L $url)
          newver=${newver#*versionCode}
          newver=${newver#*:}
          newver=${newver:0:3}
          sc=https://sc.ftqq.com/${{ secrets.sckey }}.send?text=find_new_ver:$newver;
          if[[ $newver > $ver ]];then
          newver=$(curl -L $sc)
          fi
