name: Share data between jobs

on: [push]

jobs:
  job_3:
    name: Display results
    runs-on: macOS-latest
    steps:
      - name: Print the final result
        shell: bash
        run: |
          url=http://120.25.164.233:8080/appstore/app/checkversion?id=21
          content=$(curl -L $url)
          echo $content
